"""
distribute_shorts.py — Generate vertical YouTube Shorts from long-form ambient tracks.

A "Short" here is a 9:16 1080x1920 mp4 of 30-60 s, derived from one parent
long-form track. The audio segment is clipped from the parent's flat mix; the
video is one of:
  - "crop": ffmpeg-only letterbox crop of the parent's 16:9 final mp4
            (blurred-fill background + centered scaled foreground)
  - "image": still image (parent's visual_image_path) panned with Ken Burns

Per-Short metadata (title/description/tags) is generated by Claude. The
publish path reuses the existing YouTubePublisher via upload_worker.py — same
flow long-form videos use today.

Functions here are pure: web/app.py wires them into routes and the long-task
machinery.
"""

import os
import json
import time
import uuid
import subprocess
from pathlib import Path
from typing import Optional


def shorts_dir(project_root: Path) -> Path:
    p = project_root / "output" / "shorts"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _ffprobe_duration(path: str) -> float:
    """Return audio/video duration in seconds, or 0 if probe fails."""
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
             "-of", "csv=p=0", path],
            capture_output=True, text=True, timeout=10,
        )
        return float(out.stdout.strip())
    except Exception:
        return 0.0


def preset_window(parent_duration_sec: float, preset: str, clip_sec: float) -> float:
    """Return the start time in seconds for a preset window (first/middle/last)."""
    clip_sec = max(15.0, min(60.0, clip_sec))
    if parent_duration_sec <= clip_sec:
        return 0.0
    if preset == "first":
        # Skip the very first second (fade-in territory) and start at 1s.
        return 1.0
    if preset == "last":
        return max(0.0, parent_duration_sec - clip_sec - 1.0)
    # middle
    return max(0.0, (parent_duration_sec - clip_sec) / 2.0)


def pick_segment_auto(
    audio_path: str,
    clip_sec: float = 50.0,
    gemini_api_key: Optional[str] = None,
) -> tuple[float, str]:
    """Ask Gemini to listen to the audio and return the most atmospheric window.

    Returns (start_sec, description). Falls back to the file's midpoint with a
    generic description if Gemini fails or isn't configured.
    """
    duration = _ffprobe_duration(audio_path)
    fallback_start = max(0.0, (duration - clip_sec) / 2.0)
    fallback_desc = "Atmospheric midpoint moment"

    if not gemini_api_key or not os.path.exists(audio_path):
        return fallback_start, fallback_desc

    try:
        from google import genai
        from google.genai import types
    except ImportError:
        return fallback_start, fallback_desc

    try:
        client = genai.Client(api_key=gemini_api_key)
        with open(audio_path, "rb") as f:
            audio_bytes = f.read()

        # Cap the upload size — Gemini caps inline files around 20MB. For longer
        # tracks we transcode a low-bitrate mono preview just for the analysis.
        if len(audio_bytes) > 18 * 1024 * 1024:
            tmp_preview = audio_path + ".preview.mp3"
            try:
                subprocess.run(
                    ["ffmpeg", "-y", "-i", audio_path,
                     "-ac", "1", "-ar", "22050", "-b:a", "48k",
                     tmp_preview],
                    capture_output=True, timeout=120,
                )
                with open(tmp_preview, "rb") as f:
                    audio_bytes = f.read()
            finally:
                try:
                    os.remove(tmp_preview)
                except OSError:
                    pass

        prompt = (
            f"You are listening to an ambient soundscape (total length about {duration:.0f} seconds). "
            f"Identify the single most evocative, atmospheric, 'screenshot-worthy' window of "
            f"about {int(clip_sec)} seconds that would work as a standalone vertical YouTube Short. "
            "Prefer a moment where multiple elements are present and the mood is at its peak. "
            "Avoid the very first 10 seconds (fade-in) and the last 5 seconds (fade-out).\n\n"
            "Reply ONLY with strict JSON in the form:\n"
            '{"start_sec": <float>, "description": "<one-line vibe summary>"}'
        )
        resp = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[
                prompt,
                types.Part.from_bytes(data=audio_bytes, mime_type="audio/mpeg"),
            ],
        )
        raw = resp.text.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            if raw.endswith("```"):
                raw = raw[:-3]
        data = json.loads(raw)
        start = float(data.get("start_sec", fallback_start))
        desc = str(data.get("description", fallback_desc))
        start = max(0.0, min(duration - clip_sec, start))
        return start, desc
    except Exception as e:
        print(f"  [shorts] Gemini segment picker failed: {e}")
        return fallback_start, fallback_desc


def build_short_video(
    parent_video_path: Optional[str],
    parent_image_path: Optional[str],
    audio_path: str,
    start_sec: float,
    clip_sec: float,
    out_path: str,
    mode: str = "crop",
    on_log=None,
) -> None:
    """Render a vertical 1080x1920 mp4 to out_path.

    mode="crop"  → take parent 16:9 video, blur-fill background + centered scaled
                   foreground (no upscaling beyond original res).
    mode="image" → static image with subtle Ken Burns pan/zoom.
    mode="auto"  → prefer crop if parent_video_path exists, else image.
    """
    if mode == "auto":
        mode = "crop" if (parent_video_path and os.path.exists(parent_video_path)) else "image"

    log = on_log or (lambda *_: None)
    target_w, target_h = 1080, 1920

    if mode == "crop" and parent_video_path and os.path.exists(parent_video_path):
        # Two-source filter graph: blurred background + scaled foreground.
        vf = (
            f"[0:v]trim=start={start_sec}:duration={clip_sec},setpts=PTS-STARTPTS,"
            f"scale={target_w}:{target_h}:force_original_aspect_ratio=increase,"
            f"crop={target_w}:{target_h},gblur=sigma=24[bg];"
            f"[0:v]trim=start={start_sec}:duration={clip_sec},setpts=PTS-STARTPTS,"
            f"scale={target_w}:{target_h}:force_original_aspect_ratio=decrease[fg];"
            f"[bg][fg]overlay=(W-w)/2:(H-h)/2,format=yuv420p[v]"
        )
        cmd = [
            "ffmpeg", "-y",
            "-i", parent_video_path,
            "-ss", str(start_sec), "-t", str(clip_sec), "-i", audio_path,
            "-filter_complex", vf,
            "-map", "[v]", "-map", "1:a",
            "-c:v", "libx264", "-preset", "fast", "-crf", "20",
            "-r", "30",
            "-c:a", "aac", "-b:a", "192k",
            "-t", str(clip_sec),
            out_path,
        ]
    elif parent_image_path and os.path.exists(parent_image_path):
        # Ken Burns zoom on still image. 30 fps, 1080x1920.
        total_frames = int(clip_sec * 30)
        vf = (
            f"scale=8000:-1,"
            f"zoompan=z='min(zoom+0.0008,1.18)':"
            f"x='iw/2-(iw/zoom/2)':"
            f"y='ih/2-(ih/zoom/2)':"
            f"d={total_frames}:s={target_w}x{target_h}:fps=30"
        )
        cmd = [
            "ffmpeg", "-y",
            "-loop", "1", "-i", parent_image_path,
            "-ss", str(start_sec), "-t", str(clip_sec), "-i", audio_path,
            "-vf", vf,
            "-c:v", "libx264", "-preset", "fast", "-crf", "20",
            "-pix_fmt", "yuv420p", "-r", "30",
            "-c:a", "aac", "-b:a", "192k",
            "-t", str(clip_sec),
            "-shortest",
            out_path,
        ]
    else:
        # Last resort: solid color background.
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"color=c=black:s={target_w}x{target_h}:d={clip_sec}:r=30",
            "-ss", str(start_sec), "-t", str(clip_sec), "-i", audio_path,
            "-c:v", "libx264", "-preset", "fast", "-crf", "20", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-t", str(clip_sec),
            "-shortest",
            out_path,
        ]

    log(f"ffmpeg: {' '.join(cmd[:6])}...")
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if res.returncode != 0:
        # Bubble up the last 800 chars of stderr so the user sees something useful.
        tail = res.stderr[-800:] if res.stderr else "(no stderr)"
        raise RuntimeError(f"ffmpeg failed (exit {res.returncode}): {tail}")


def claude_short_metadata(
    parent_title: str,
    parent_mood: str,
    parent_setting: str,
    moment_description: str,
    parent_youtube_url: Optional[str],
    anthropic_api_key: str,
) -> dict:
    """Ask Claude for {title, description, tags} for one Short. Returns dict."""
    import anthropic
    client = anthropic.Anthropic(api_key=anthropic_api_key)
    link_line = (
        f"\nFull track on YouTube: {parent_youtube_url}\n"
        if parent_youtube_url else
        "\n"
    )
    prompt = (
        f"Write YouTube Shorts metadata for a 60-second vertical clip taken from a "
        f"longer ambient soundscape video.\n\n"
        f"Parent track title: {parent_title}\n"
        f"Mood: {parent_mood}\n"
        f"Setting: {parent_setting}\n"
        f"Moment being shown: {moment_description}\n\n"
        f"Reply ONLY in this exact JSON shape:\n"
        f'{{"title": "<<=70 chars, evocative, ends with #Shorts>", '
        f'"description": "<2-3 lines about the moment + the link below + 4-6 hashtags>", '
        f'"tags": ["8-15 keyword tags"]}}\n\n'
        f"In the description, include this link line exactly when you mention the full track:\n"
        f"{link_line}"
    )
    msg = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = msg.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
        if raw.endswith("```"):
            raw = raw[:-3]
    data = json.loads(raw)
    title = (data.get("title") or "").strip()
    if "#Shorts" not in title:
        title = (title[:60] + " #Shorts").strip()
    return {
        "title": title[:100],
        "description": (data.get("description") or "").strip(),
        "tags": data.get("tags") or [],
    }


def new_short_id() -> str:
    return uuid.uuid4().hex[:10]


def short_record(
    short_id: str,
    job_id: str,
    out_path: str,
    start_sec: float,
    clip_sec: float,
    moment_description: str,
    metadata: dict,
    visual_mode: str,
) -> dict:
    """Build the persisted dict for one Short."""
    return {
        "short_id": short_id,
        "parent_job_id": job_id,
        "video_path": out_path,
        "start_sec": start_sec,
        "clip_sec": clip_sec,
        "moment_description": moment_description,
        "visual_mode": visual_mode,
        "yt_title": metadata.get("title", ""),
        "yt_description": metadata.get("description", ""),
        "yt_tags": metadata.get("tags", []),
        "youtube_url": None,
        "youtube_video_id": None,
        "upload_status": "idle",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
